### ISSUE TITLE
Router Link for Column Template component

### ISSUE THREAD

**Issue by wilsonna** [JitBlox/Issues#12]
**Is your feature request related to a problem? Please describe.**
Currently unable to navigate to another page by clicking on a table row

**Describe the solution you'd like**
Support router link (with parameters) for Column Template so that we can navigate to different pages by clicking on the column values.

**Comment by mdelaat** [comment]
You are right, JitBlox currently only supports text-only column templates for Material tables. I will look into how to enhance this.

**Comment by mdelaat** [comment]
An Angular Material Table column template can now be customized using a _Header template_ and a _Data cell template_. This opens up the possibility to add route links inside a data cell. I've created a [basic example](https://www.jitblox.com/design/AYKSUOd3BU) in which the ID of each record is passed to a property of a "detail" component.
