### ISSUE TITLE
Allow importing mock data as JSON

### ISSUE THREAD

**Issue by psupina** [JitBlox/Issues#14]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I refactor my data model or API stubs and I want to use some part of mock data I have already created somewhere else.

**Describe the solution you'd like**
In the "Mock data set" dialog, I want to have an option to import one or more rows from a text area formatted as JSON (either {} or [ {}, {} ] ).

**Describe alternatives you've considered**
None.

**Additional context**
Ex. I have an API stub _getAddress_ using mock data for a postal address with a type **PostalAddress**.
Afterwards, I decide to create a new type **Customer** which includes a field for a postal address and an API stub _getCustomer_. I will create a mock data for this new API stub and I would like to copy my existing postal address mock data into the new customer mock data.
I am already able to see this postal address as JSON in the source code for the mock data. But I am unable to use this JSON while creating new mock data sets.

![image](https://user-images.githubusercontent.com/8601627/128834749-72ac2101-6a04-4d50-b967-93627a829e1a.png)

**Comment by bullwinkle** [comment]
Really important one

**Comment by mdelaat** [comment]
@psupina @bullwinkle  I started development of a JSON editing feature that works for any complex object and covers this use case. It will work as follows:
 1. At any level in the mock data editor, click "Edit as JSON" in the bottom right corner. 
 
![Import JSON button](https://user-images.githubusercontent.com/36327340/135476349-f8bbe307-a8e1-4769-ac97-cad7deca2169.PNG) 
 
2. This will bring up a simple (no syntax highlighting) text input that allows copy/pasting JSON  data. Any malformed JSON won't be imported, and neither will properties that are not part of the current type (these will simply be ignored).

![Import JSON dialog](https://user-images.githubusercontent.com/36327340/135476393-42d716db-b5d0-4c8a-949f-9bd1cc2a0e7a.PNG)

This feature is planned for the next release (in the course of next week).

**Comment by mdelaat** [comment]
JSON editing/importing is available now in version 0.24.0.

**Comment by psupina** [comment]
@mdelaat Thank you. I have just tested it.
The JSON editing/importing works as you described earlier and the functionality meets my needs. :thumbsup:

I suggest mentioning this feature in the [Docs](https://www.jitblox.com/docs/api-stubs#mock-data) and/or posting a new blog article about this new feature.
